name: aqar_user
description: تطبيق توثيق العقار
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # =========================
  # Provider
  # =========================
  provider: ^6.0.5

  # =========================
  # Images Picker
  # =========================
  image_picker: ^1.0.7

  # =========================
  # Internet Connectivity
  # =========================
  connectivity_plus: ^6.0.5

  # =========================
  # Fast Login (Biometrics + Secure Storage + Hash)
  # =========================
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3

  # =========================
  # Localization (L10n)
  # =========================
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # =========================
  # UI / Utils
  # =========================
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

  # =========================
  # Supabase
  # =========================
  supabase_flutter: ^2.12.0

  # =========================
  # Env
  # =========================
  flutter_dotenv: ^5.1.0

  # =========================
  # File / Media
  # =========================
  file_picker: ^10.3.10
  image: ^4.1.7

  # =========================
  # Device info
  # =========================
  device_info_plus: ^10.1.0

  # =========================
  # Utilities
  # =========================
  uuid: ^4.5.2

  # =========================
  # Maps
  # =========================
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.10

  # =========================
  # GPS / Location
  # =========================
  geolocator: ^11.0.0

  # =========================
  # Sharing
  # =========================
  share_plus: ^10.0.2

  # =========================
  # OTP
  # =========================
  sms_autofill: ^2.4.1
  pin_code_fields: ^8.0.1

  # =========================
  # Screen Security (Android + iOS)
  # =========================
  no_screenshot: ^0.2.0

  # =========================
  # Firebase & Notifications
  # =========================
  # ملاحظة: تم دمج وتحديث الإصدارات لتتوافق مع آخر عملية تثبيت قمت بها
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^17.2.3
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/splashscreen.png
    - assets/Black Saudi Riyal.png
    - assets/White Saudi riyal.png
    - assets/sounds/otp.wav
    - assets/sounds/otp.mp3